#!/usr/bin/python
"""
  Runscript for TEMimage

  Copyright (c) 2013, rhambach. 
    This file is part of the TEMimage package and released
    under the MIT-Licence. See LICENCE file for details.
"""
import sys
import tifffile as tiff
from gui_interaction import GUI

# get filenames from commandline
if len(sys.argv)<2:
  print "Usage: FitAtomPos <TIF-raw> [<TIF-filtered>]";
  sys.exit(0);
rawfile = sys.argv[1];
infile  = sys.argv[2] if len(sys.argv)==3 else rawfile;

# start GUI
GUI(infile,rawfile).start();
